# LICENSE: THE SHOVEL
# This software is developed for educational and authorized offensive security reconnaissance.

import json
import argparse
import sys
from datetime import datetime
from rich.console import Console

console = Console()

class ReportCompiler:
    def __init__(self, json_file):
        self.json_file = json_file
        self.data = self._load_data()

    def _load_data(self):
        try:
            with open(self.json_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            console.print(f"[bold red][!] Failed to load JSON data: {e}[/bold red]")
            sys.exit(1)

    def generate_markdown(self):
        target = self.data.get("target", "Unknown")
        ip = self.data.get("ip_address", "Unknown")
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"# Automated Reconnaissance Assessment: {target}\n"
        md += f"**Date of Assessment:** {date} | **Target IP:** {ip}\n\n"
        md += "---\n\n"
        
        md += "## 1. Executive Summary\n"
        md += f"This report details the external attack surface, infrastructure footprint, and human intelligence gathered for `{target}`. The objective is to identify systemic misconfigurations, exposed sensitive endpoints, and social engineering risk profiles.\n\n"

        # Vulnerabilities
        fuzzer_data = self.data.get("fuzzer_exposures", [])
        if fuzzer_data:
            md += "## 2. High-Value Path Exposures (Critical/High Risk)\n"
            md += "The following endpoints are exposing sensitive configuration files, internal paths, or default server status pages.\n\n"
            md += "| URL | Status | Severity | Risk Description |\n"
            md += "|---|---|---|---|\n"
            for hit in fuzzer_data:
                url = hit['url']
                status = hit['status']
                severity = "High" if "phpinfo" in url or ".env" in url or ".git" in url else "Medium"
                desc = "Information Disclosure / Configuration Leak"
                md += f"| `{url}` | {status} | **{severity}** | {desc} |\n"
            md += "\n"

        # Identity OSINT
        identity_data = self.data.get("identity_osint", {})
        if identity_data and "contacts" in identity_data:
            contacts = identity_data["contacts"]
            md += "## 3. Human Attack Surface & Social Engineering Risk\n"
            md += f"Identified **{len(contacts)}** corporate identities. This intelligence dictates the organization's vulnerability to targeted spear-phishing and credential stuffing attacks.\n\n"
            md += "| Name | Position | Department | Email |\n"
            md += "|---|---|---|---|\n"
            for c in contacts:
                md += f"| {c.get('first_name')} {c.get('last_name')} | {c.get('position')} | {c.get('department')} | `{c.get('email')}` |\n"
            md += "\n"

        # Subdomains
        subdomains = self.data.get("fingerprinted_subdomains", [])
        live_subs = [s for s in subdomains if str(s.get("status")) != "DEAD"]
        if live_subs:
            md += "## 4. Live Infrastructure Footprint\n"
            md += f"Successfully mapped **{len(live_subs)}** live subdomains/virtual hosts.\n\n"
            md += "| Subdomain | Status | Server Tech |\n"
            md += "|---|---|---|\n"
            for s in live_subs:
                md += f"| `{s.get('subdomain')}` | {s.get('status')} | {s.get('server')} |\n"
            md += "\n"

        md += "---\n*Report generated by THE SHOVEL OSINT Framework.*\n"
        return md

    def export(self):
        target = self.data.get("target", "Unknown")
        output_file = f"{target}_report.md"
        md_content = self.generate_markdown()
        
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(md_content)
            console.print(f"[bold green][+] Professional Red Team report compiled: {output_file}[/bold green]")
        except Exception as e:
            console.print(f"[bold red][!] Export failed: {e}[/bold red]")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="THE SHOVEL - Report Compiler")
    parser.add_argument("-i", "--input", help="The raw JSON intelligence file", required=True)
    args = parser.parse_args()
    
    compiler = ReportCompiler(args.input)
    compiler.export()