# LICENSE: THE SHOVEL
# This software is developed for educational and authorized offensive security reconnaissance.

import json
import argparse
import sys
from datetime import datetime
from rich.console import Console

console = Console()

class ReportCompiler:
    def __init__(self, data=None, json_file=None):
        if json_file:
            self.data = self._load_data(json_file)
        else:
            self.data = data or {}

    def _load_data(self, filepath):
        try:
            with open(filepath, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            console.print(f"[bold red][!] Failed to load JSON data: {e}[/bold red]")
            sys.exit(1)

    def generate_markdown(self):
        target = self.data.get("target", "Unknown")
        ip = self.data.get("ip_address", "Unknown")
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        md = f"# Security Assessment Report: {target}\n"
        md += f"**Date:** {date} | **Primary IP:** {ip}\n\n"
        md += "---\n\n"
        
        md += "## 1. Executive Summary\n"
        md += f"High-level reconnaissance of `{target}` identified multiple critical misconfigurations. The primary risks involve **source code exposure** and **internal system disclosure** via unhardened subdomains.\n\n"

        # --- VULNERABILITIES (CLEANED) ---
        fuzzer_data = self.data.get("fuzzer_exposures", [])
        # Filter for actual exposures (Status 200) and ignore noise like robots.txt
        critical_hits = [h for h in fuzzer_data if h['status'] == 200 and "robots.txt" not in h['url']]
        
        if critical_hits:
            md += "## 2. Critical Information Disclosures\n"
            md += "The following endpoints were successfully accessed (Status 200) and are leaking sensitive internal data.\n\n"
            md += "| Severity | Vulnerable URL | Impact |\n"
            md += "|---|---|---|\n"
            for hit in critical_hits:
                url = hit['url']
                if ".git" in url:
                    severity, impact = "CRITICAL", "Full Source Code Disclosure"
                elif "phpinfo" in url:
                    severity, impact = "HIGH", "Internal Environment & Path Disclosure"
                elif ".env" in url:
                    severity, impact = "CRITICAL", "Credential & API Key Leakage"
                else:
                    severity, impact = "MEDIUM", "Information Disclosure"
                
                md += f"| **{severity}** | `{url}` | {impact} |\n"
            md += "\n"
        else:
            md += "## 2. Critical Information Disclosures\n"
            md += "No critical file exposures (200 OK) were identified during this pass.\n\n"

        # --- IDENTITY ---
        identity_data = self.data.get("identity_osint", {})
        if identity_data and "contacts" in identity_data:
            contacts = identity_data["contacts"]
            md += "## 3. Personnel Intelligence\n"
            md += f"Mapped **{len(contacts)}** key corporate identities. These targets are high-priority for spear-phishing based on their technical or executive roles.\n\n"
            md += "| Name | Title | Email |\n"
            md += "|---|---|---|\n"
            for c in contacts[:10]: # Limit to top 10 for readability
                md += f"| {c.get('first_name')} {c.get('last_name')} | {c.get('position')} | `{c.get('email')}` |\n"
            md += "\n"

        # --- INFRASTRUCTURE ---
        subdomains = self.data.get("fingerprinted_subdomains", [])
        live_subs = [s for s in subdomains if str(s.get("status")) != "DEAD"]
        if live_subs:
            md += "## 4. Attack Surface Footprint\n"
            md += f"A total of **{len(live_subs)}** live assets were identified. A significant number of these are running potentially outdated `nginx` or `Apache` instances.\n\n"
            md += "| Subdomain | Status | Tech Stack |\n"
            md += "|---|---|---|\n"
            # Show only the first 15 live ones in the report to keep it punchy
            for s in live_subs[:15]:
                md += f"| `{s.get('subdomain')}` | {s.get('status')} | {s.get('server')} |\n"
            md += "\n"

        md += "---\n*Generated by THE SHOVEL Framework.*\n"
        return md

    def export(self):
        target = self.data.get("target", "Unknown")
        output_file = f"{target}_report_v2.md"
        md_content = self.generate_markdown()
        
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(md_content)
            return output_file
        except Exception as e:
            console.print(f"[bold red][!] Export failed: {e}[/bold red]")
            return None